Repository mishka-group/mishka-cms, pull requests merged in 2021-09, with the labels that each got.

#77 fix typo
  apps/mishka_user/lib/token/phoenix_token.ex
Labels: bug

#82 Create Admin Live CRUD UI Macro
  apps/mishka_content/lib/blog/tag.ex
  apps/mishka_content/lib/general/comment.ex
  apps/mishka_database/lib/public/setting_agent.ex
  apps/mishka_html/lib/mishka_html/helpers/live_crud.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_categories_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_category_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_post_authors_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_post_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_post_tags_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_posts_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_tag_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_tags_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_comment_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_comments_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_dashboard_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_link_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_links_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_log_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_logs_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_media_manager_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_seo_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_setting_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_settings_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_subscription_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_subscriptions_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_user_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_user_role_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_user_role_permissions_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_user_roles_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_users_live.ex
  apps/mishka_html/lib/mishka_html_web/live/components/admin/blog/category/list_component.ex
  apps/mishka_html/lib/mishka_html_web/live/components/admin/blog/post/lists_component.ex
  apps/mishka_html/lib/mishka_html_web/live/components/admin/dashboard/admin_last_notif_component.ex
  apps/mishka_html/lib/mishka_html_web/templates/admin_blog/admin_blog_post_live.html.leex
  apps/mishka_html/lib/mishka_html_web/templates/admin_blog/admin_blog_posts_live.html.leex
  apps/mishka_html/lib/mishka_html_web/templates/admin_user/admin_users_live.html.leex
  apps/mishka_html/mix.exs
  apps/mishka_user/lib/acl/user_role.ex
  apps/mishka_user/lib/token/token_managemnt.ex
Labels: bug, documentation, enhancement, help wanted, dependencies

#103 improve guardian auth_pipeline and add draft macro and state
  apps/mishka_api/lib/mishka_api_web/router.ex
  apps/mishka_content/lib/cache/content_draft_dynamic_supervisor.ex
  apps/mishka_content/lib/cache/content_draft_management.ex
  apps/mishka_content/lib/mishka_content/application.ex
  apps/mishka_content/mix.exs
  apps/mishka_html/assets/css/app.css
  apps/mishka_html/lib/mishka_html/helpers/live_crud.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_category_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_post_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_tag_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_comment_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_link_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_setting_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_subscription_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_user_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_user_role_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_user_role_permissions_live.ex
  apps/mishka_html/lib/mishka_html_web/live/components/admin/public/draft_block_component.ex
  apps/mishka_html/lib/mishka_html_web/templates/admin_blog/admin_blog_category_live.html.leex
  apps/mishka_html/lib/mishka_html_web/templates/admin_blog/admin_blog_post_live.html.leex
  apps/mishka_html/lib/mishka_html_web/templates/admin_blog/admin_blog_tag_live.html.leex
  apps/mishka_html/lib/mishka_html_web/templates/admin_blog/admin_link_live.html.leex
  apps/mishka_html/lib/mishka_html_web/templates/admin_comment/admin_comment_live.html.leex
  apps/mishka_html/lib/mishka_html_web/templates/admin_subscription/admin_subscription_live.html.leex
  apps/mishka_html/lib/mishka_html_web/templates/admin_user/admin_user_live.html.leex
  apps/mishka_user/lib/guardian/auth_error_handler.ex
  apps/mishka_user/lib/guardian/auth_pipeline.ex
Labels: bug, enhancement

#104 Add some new lines of Admin Draft to translate
  apps/mishka_translator/priv/gettext/en/LC_MESSAGES/html_live.po
  apps/mishka_translator/priv/gettext/en/LC_MESSAGES/html_live_component.po
  apps/mishka_translator/priv/gettext/en/LC_MESSAGES/html_live_templates.po
  apps/mishka_translator/priv/gettext/en/LC_MESSAGES/user_captcha.po
  apps/mishka_translator/priv/gettext/fa/LC_MESSAGES/html_live.po
  apps/mishka_translator/priv/gettext/fa/LC_MESSAGES/html_live_component.po
  apps/mishka_translator/priv/gettext/fa/LC_MESSAGES/html_live_templates.po
  apps/mishka_translator/priv/gettext/fa/LC_MESSAGES/user_captcha.po
  apps/mishka_translator/priv/gettext/html_live.pot
  apps/mishka_translator/priv/gettext/html_live_component.pot
  apps/mishka_translator/priv/gettext/html_live_templates.pot
  apps/mishka_translator/priv/gettext/user_captcha.pot
Labels: enhancement

#106 Add option to delete state of draft after saving
  apps/mishka_html/assets/static/css/default-template.css
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_category_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_blog_post_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_comment_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_link_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_setting_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_subscription_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_user_live.ex
  apps/mishka_html/lib/mishka_html_web/live/admin_user_role_live.ex
  apps/mishka_html/lib/mishka_html_web/live/components/admin/form/editor_component.ex
Labels: bug

#107 Restructure installer and add nginx web server for production
  deployment/docker/Dockerfile
  deployment/docker/docker-compose_with_nginx.yml
  deployment/docker/docker-compose_without_nginx.yml
  deployment/docker/entrypoint.sh
  deployment/docker/mishka.sh
  deployment/docker/nginx/conf/conf.d/default.conf
  deployment/docker/nginx/conf/conf.d/mishka_api.conf
  deployment/docker/nginx/conf/conf.d/mishka_cms.conf
  deployment/docker/nginx/conf/fastcgi.conf
  deployment/docker/nginx/conf/fastcgi_params
  deployment/docker/nginx/conf/mime.types
  deployment/docker/nginx/conf/modules
  deployment/docker/nginx/conf/nginx.conf
  deployment/docker/nginx/conf/scgi_params
  deployment/docker/nginx/conf/uwsgi_params
  mishka.sh
Labels: enhancement

#108 Add docker Persian installer Read me part
  README_FA.md
Labels: enhancement
